# Generated by Django 3.1.2 on 2020-11-05 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_header', models.CharField(max_length=50)),
                ('topic_body', models.TextField(blank=True, null=True)),
                ('topic_createdtime', models.DateTimeField(auto_now_add=True)),
                ('topic_lastmodified', models.DateTimeField(blank=True, null=True)),
                ('topic_tag', models.ManyToManyField(blank=True, null=True, related_name='topic_tag', to='tags.Tag')),
                ('topic_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
