# Generated by Django 3.1.2 on 2020-11-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_lastmodified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
